version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # environment:
    #   - DATABASE_URL=mysql://root:root@db:3306/geolocserver
    networks:
      - app_network

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'geolocserver'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
    # https://github.com/docker-library/mysql/issues/579
    ulimits:
      nproc: 65535
      nofile:
        soft: 26677
        hard: 46677
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  dbdata:
